const AETH_ADDRESS='0xAb5ae0D8f569d7c2B27574319b864a5bA6F9671e',STAKING_ADDRESS='0x896D9d37A67B0bBf81dde0005975DA7850FFa638',AETH_ABI=['function balanceOf(address) view returns (uint256)','function totalSupply() view returns (uint256)'],STAKING_ABI=['function getUserStakesCount(address) view returns (uint256)','function getUserStake(address, uint256) view returns (uint256, uint256, uint256, uint256, uint256, uint256)','function totalStaked() view returns (uint256)'];
let provider,currentTab='holders';
const mockLeaderboardData={holders:[{address:'0x8A3a...3452',value:'125,450,000',percentage:'12.5%',badges:['whale','og'],rank:1},{address:'0x6F2B...8971',value:'98,320,500',percentage:'9.8%',badges:['whale','diamond'],rank:2},{address:'0x4D8E...1234',value:'75,890,200',percentage:'7.6%',badges:['whale'],rank:3},{address:'0x9C3F...5678',value:'52,100,000',percentage:'5.2%',badges:['og'],rank:4},{address:'0x2A7D...9012',value:'41,500,000',percentage:'4.2%',badges:['diamond'],rank:5},{address:'0x5B1C...3456',value:'35,200,000',percentage:'3.5%',badges:[],rank:6},{address:'0x7E4F...7890',value:'28,900,000',percentage:'2.9%',badges:[],rank:7},{address:'0x8D2A...2345',value:'22,100,000',percentage:'2.2%',badges:['og'],rank:8},{address:'0x3F5E...6789',value:'18,500,000',percentage:'1.9%',badges:[],rank:9},{address:'0x1C6B...0123',value:'15,200,000',percentage:'1.5%',badges:[],rank:10}],stakers:[{address:'0x4D8E...1234',value:'45,890,200',duration:'180 days',badges:['diamond'],rank:1},{address:'0x8A3a...3452',value:'38,450,000',duration:'90 days',badges:['whale','og'],rank:2},{address:'0x6F2B...8971',value:'32,320,500',duration:'180 days',badges:['diamond'],rank:3}],traders:[{address:'0x2A7D...9012',value:'$125,450',trades:'342',badges:['whale'],rank:1},{address:'0x5B1C...3456',value:'$98,320',trades:'289',badges:[],rank:2},{address:'0x7E4F...7890',value:'$75,890',trades:'215',badges:['og'],rank:3}],referrers:[{address:'0x9C3F...5678',value:'42',rewards:'125,000 AETH',badges:['og'],rank:1},{address:'0x8D2A...2345',value:'35',rewards:'98,000 AETH',badges:[],rank:2},{address:'0x3F5E...6789',value:'28',rewards:'75,000 AETH',badges:[],rank:3}]};
function el(tag,{className,text,attrs}={}){const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=String(text);if(attrs)Object.entries(attrs).forEach(([k,v])=>{if(v!==undefined&&v!==null)n.setAttribute(k,String(v));});return n;}
function clear(node){if(node)node.replaceChildren();}
function rankLabel(rank){if(rank<=3)return rank===1?'🥇':rank===2?'🥈':'🥉';return '#'+rank;}
function badgeNode(type){if(type==='whale'){const b=el('span',{className:'badge badge-whale'});b.append(el('i',{className:'fas fa-water'}),document.createTextNode(' Whale'));return b;}if(type==='og'){const b=el('span',{className:'badge badge-og'});b.append(el('i',{className:'fas fa-crown'}),document.createTextNode(' OG'));return b;}if(type==='diamond'){const b=el('span',{className:'badge badge-diamond'});b.append(el('i',{className:'fas fa-gem'}),document.createTextNode(' Diamond Hands'));return b;}return null;}
function statLabel(item,tab){if(tab==='holders')return 'AETH Tokens';if(tab==='stakers')return item.duration;if(tab==='traders')return item.trades+' trades';if(tab==='referrers')return 'referrals';return '';}
function renderLeaderItem(item,tab){const root=el('div',{className:'leader-item'});const rank=el('div',{className:`rank ${item.rank<=3?'rank-'+item.rank:''}`,text:rankLabel(item.rank)});const info=el('div',{className:'leader-info'});info.append(el('div',{className:'leader-address',text:item.address}));const badges=el('div',{className:'leader-badges'});item.badges.map(badgeNode).filter(Boolean).forEach((b)=>badges.appendChild(b));info.appendChild(badges);const stats=el('div',{className:'leader-stats'});stats.append(el('div',{className:'stat-value',text:item.value}),el('div',{className:'stat-label',text:statLabel(item,tab)}));if(item.percentage)stats.appendChild(el('div',{className:'stat-label',text:item.percentage+' of supply'}));if(item.rewards)stats.appendChild(el('div',{className:'stat-label',text:item.rewards+' earned'}));root.append(rank,info,stats);return root;}
function renderLoading(container,message,iconClass){clear(container);const wrap=el('div',{className:'loading'});const icon=el('i',{className:iconClass,attrs:{style:iconClass.includes('spinner')?'':'font-size: 3rem; opacity: 0.5;'}});wrap.append(icon,el('p',{text:message,attrs:{style:'margin-top: 1rem;'}}));container.appendChild(wrap);}
function switchTab(tab,eventArg){currentTab=tab;document.querySelectorAll('.tab').forEach((node)=>node.classList.remove('active'));const targetEvent=eventArg||window.event;if(targetEvent?.target?.closest)targetEvent.target.closest('.tab').classList.add('active');document.getElementById('categoryTitle').textContent={holders:'Top Holders',stakers:'Top Stakers',traders:'Top Traders',referrers:'Top Referrers'}[tab];loadLeaderboard(tab);}
function loadLeaderboard(tab){const container=document.getElementById('leaderboardContent'),items=mockLeaderboardData[tab];if(!container)return;clear(container);if(items&&items.length){items.forEach((item)=>container.appendChild(renderLeaderItem(item,tab)));}else{renderLoading(container,'No data available yet','fas fa-inbox');}}
function refreshLeaderboard(){const container=document.getElementById('leaderboardContent');if(container)renderLoading(container,'Refreshing...','fas fa-spinner loading-spinner');setTimeout(()=>loadLeaderboard(currentTab),1000);}
window.switchTab=switchTab;window.refreshLeaderboard=refreshLeaderboard;window.addEventListener('load',()=>{loadLeaderboard('holders');});