const fs = require('fs');
function read(name) { return fs.readFileSync(name, 'utf8'); }
function assert(condition, message) { if (!condition) { console.error(`Launch-gate test failed: ${message}`); process.exit(1); } }
const canonical = '0xecf7E17faE148C01E1b5008A31Dfd2d1B6608E4e';
const legacy = '0xAb5ae0D8f569d7c2B27574319b864a5bA6F9671e';
const index = read('index.html');
const indexJs = read('index.js');
const overrides = read('index-dom-overrides.js');
const config = read('presale-config.js');
const readiness = read('presale-readiness.js');
const analyticsEntry = read('vercel-analytics.entry.mjs');
const marketing = read('marketing-launch.js');
const verifier = read('smart-contract/scripts/verify-base-presale-state.mjs');
assert(index.includes(canonical), 'homepage must publish the canonical Base AETH address');
assert(indexJs.includes(canonical), 'homepage runtime must fall back to the canonical Base AETH address');
assert(!index.includes(legacy) && !indexJs.includes(legacy), 'legacy Polygon AETH address must not appear in public homepage runtime');
assert(!index.includes('Polygon Mainnet'), 'public homepage must not identify Polygon as production');
assert(index.includes('Base Mainnet (Chain ID: 8453)'), 'homepage Base instructions must publish chain ID 8453');
assert(/launchAuthorized:\s*true/.test(config), 'presale config must reflect owner approval');
assert(/purchaseAuthorized:\s*false/.test(config), 'expired presale window must keep public purchases disabled');
assert(/tradingAuthorized:\s*true/.test(config), 'trading must be product-authorized');
assert(/liquidityAuthorized:\s*false/.test(config), 'canonical liquidity must remain unauthorized until a pool is verified');
assert(/launchAuthorized:\s*true/.test(analyticsEntry), 'analytics entry must reflect authorization');
assert(/purchaseAuthorized:\s*false/.test(analyticsEntry), 'analytics entry must publish purchases paused');
assert(analyticsEntry.includes("launchStatus: 'presale-window-ended-purchases-paused'"), 'analytics launch status must not imply the expired sale is open');
assert(/publicFundingAuthorized:\s*false/.test(marketing), 'marketing must not authorize public funding while the sale window is expired');
assert(/presalePurchaseAuthorized:\s*false/.test(marketing), 'marketing must explicitly publish purchase authorization as false');
assert(marketing.includes('return status.presalePurchaseAuthorized === true'), 'campaign launcher must use the purchase gate rather than launch approval');
assert(readiness.includes('config.launchAuthorized !== true'), 'presale readiness must still fail closed unless authorization is explicit');
assert(readiness.includes('config.purchaseAuthorized !== true'), 'presale readiness must fail closed unless purchases are explicitly enabled');
assert(verifier.includes('launchReady: deployment.launchable === true && fullyFundedForHardCap && saleLive'), 'Base verifier must not report launchReady when the sale window is closed');
assert(overrides.includes('adminPanel.remove()'), 'public homepage must remove state-changing owner controls from the rendered DOM');
assert(/canonical liquidity.*remain[s]? unavailable/i.test(overrides), 'public copy must state that canonical liquidity is unavailable');
console.log('Public launch-gate regression checks passed.');