const fs = require('fs');
function read(name) { return fs.readFileSync(name, 'utf8'); }
function assert(condition, message) { if (!condition) { console.error(`Launch-gate test failed: ${message}`); process.exit(1); } }
const canonical = '0xecf7E17faE148C01E1b5008A31Dfd2d1B6608E4e';
const legacy = '0xAb5ae0D8f569d7c2B27574319b864a5bA6F9671e';
const index = read('index.html');
const indexJs = read('index.js');
const overrides = read('index-dom-overrides.js');
const config = read('presale-config.js');
const readiness = read('presale-readiness.js');
const analyticsEntry = read('vercel-analytics.entry.mjs');
const marketing = read('marketing-launch.js');
const verifier = read('smart-contract/scripts/verify-base-presale-state.mjs');
assert(index.includes(canonical), 'homepage must publish the canonical Base AETH address');
assert(indexJs.includes(canonical), 'homepage runtime must fall back to the canonical Base AETH address');
assert(!index.includes(legacy) && !indexJs.includes(legacy), 'legacy Polygon AETH address must not appear in public homepage runtime');
assert(!index.includes('Polygon Mainnet'), 'public homepage must not identify Polygon as production');
assert(index.includes('Base Mainnet (Chain ID: 8453)'), 'homepage Base instructions must publish chain ID 8453');
assert(/launchAuthorized:\s*true/.test(config), 'presale config must reflect owner approval');
assert(/purchaseAuthorized:\s*false/.test(config), 'expired presale window must keep public purchases disabled');
assert(/tradingAuthorized:\s*true/.test(config), 'trading must be product-authorized');
assert(/liquidityAuthorized:\s*false/.test(config), 'canonical liquidity must remain unauthorized until a pool is verified');
assert(/launchAuthorized:\s*true/.test(analyticsEntry), 'analytics entry must reflect authorization');
assert(/purchaseAuthorized:\s*false/.test(analyticsEntry), 'analytics entry must publish purchases paused');
assert(analyticsEntry.includes("launchStatus: 'presale-window-ended-purchases-paused'"), 'analytics launch status must not imply the expired sale is open');
assert(/publicFundingAuthorized:\s*false/.test(marketing), 'marketing must not authorize public funding while the sale window is expired');
assert(/presalePurchaseAuthorized:\s*false/.test(marketing), 'marketing must explicitly publish purchase authorization as false');
assert(marketing.includes('return status.presalePurchaseAuthorized === true'), 'campaign launcher must use the purchase gate rather than launch approval');
assert(readiness.includes('config.launchAuthorized !== true'), 'presale readiness must still fail closed unless authorization is explicit');
assert(readiness.includes('config.purchaseAuthorized !== true'), 'presale readiness must fail closed unless purchases are explicitly enabled');
assert(verifier.includes('launchReady: deployment.launchable === true && fullyFundedForHardCap && saleLive'), 'Base verifier must not report launchReady when the sale window is closed');
assert(overrides.includes('adminPanel.remove()'), 'public homepage must remove state-changing owner controls from the rendered DOM');
assert(/canonical liquidity.*remain[s]? unavailable/i.test(overrides), 'public copy must state that canonical liquidity is unavailable');
assert(!index.includes('.00000001'), 'homepage source must not publish a fabricated AETH market price');
assert(!indexJs.includes('.00000001'), 'homepage runtime must not fall back to a fabricated AETH market price');
assert(!index.includes('100+</span> Holders'), 'homepage source must not publish a fabricated holder count');
assert(!indexJs.includes("'100+'"), 'homepage runtime must not fall back to a fabricated holder count');
assert(!index.includes('Max APY'), 'homepage source must not advertise an unlaunched staking APY');
assert(!index.includes('30 Days (5% APY)') && !index.includes('180 Days (25% APY)'), 'homepage source must not publish unlaunched staking reward rates');
assert(!index.includes('Buy: 3%') && !index.includes('Sell: 5%'), 'homepage source must not advertise V1 tax rates as live market fees');
assert(index.includes('V2 is prepared but not deployed'), 'homepage must state that V2 is prepared but not deployed');
assert(index.includes('No canonical Base liquidity pool'), 'homepage must state that no canonical Base liquidity pool exists');
assert(index.includes('refunds are available'), 'homepage must state that expired-presale refunds are available');
assert(/V2 candidate.*no transfer tax/i.test(overrides), 'runtime copy must describe the V2 candidate as no-transfer-tax');
assert(!indexJs.includes("value: ''"), 'homepage runtime must not fabricate a market-cap fallback');
assert(!indexJs.includes("value: '150M AETH Pool'"), 'homepage runtime must not advertise an unverified staking-pool size');
assert(!indexJs.includes("value: 'Growing'"), 'homepage runtime must not fabricate holder-growth status');
assert(!indexJs.includes('up to 50% APY'), 'social-share copy must not advertise unlaunched staking returns');
assert(!indexJs.includes("'30 Days (5% APY)'"), 'runtime stake labels must not advertise unlaunched APY rates');
assert(indexJs.includes('liquidityAuthorized !== true'), 'homepage market-data runtime must fail closed unless canonical liquidity is authorized');
assert(!indexJs.includes('0xd57c5E33ebDC1b565F99d06809debbf86142705D'), 'homepage runtime must not carry an unverified hardcoded liquidity-pair address');
assert(!index.includes('id="adminPanel"'), 'public homepage source must not ship owner write controls');
console.log('Public launch-gate regression checks passed.');